version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    container_name: pg

    expose:
      - "5432"
    env_file:
      - ./prebuild/pg/pg.env
    volumes:
      - ./schema_design/init.sql:/docker-entrypoint-initdb.d/init.sql


  elastic:
    image: elasticsearch:7.5.2
    container_name: es

    expose:
      - "9200"
      - "9300"
    env_file:
      - ./prebuild/es/es.env
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - JAVA_OPTS=$JAVA_OPTS

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  redis:
    image: redis:7.0-alpine3.16
    container_name: redis
    expose:
      - "6379"
    volumes:
      - cache:/data

  data_migrate:
    build: ./postgres_to_elastic/.
    container_name: etl
    env_file:
      - .env
    command: >
      bash -c "sleep 30
      && python load_pg_to_es.py"
    depends_on:
      - postgres
      - elastic
      - redis


volumes:
  cache:
    driver: local
